#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 07, 2020 01:16:17 AM CET  platform: Linux

import sys
from ui import grid_field
# from model import world

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

rt = None


def create_main_window(root, *args, **kwargs):
    global rt
    rt = root
    top_window = MainWindow(root)
    return top_window


def destroy_main_window():
    global rt
    rt.destroy()
    rt = None


class MainWindow(object):
    def __init__(self, top=None):
        self.age = 0
        self.max_age = 0
        self.speed = 1.0
        self.top = top
        """This class configures and populates the toplevel window.
           top is the toplevel containing window."""
        _bg_color = '#d9d9d9'  # X11 color: 'gray85'
        _fg_color = '#000000'  # X11 color: 'black'
        _comp_color = '#d9d9d9'  # X11 color: 'gray85'
        _ana_1_color = '#d9d9d9'  # X11 color: 'gray85'
        _ana_2_color = '#ececec'  # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bg_color)
        self.style.configure('.', foreground=_fg_color)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=[('selected', _comp_color),
                                        ('active', _ana_2_color)])

        self.top.geometry("1215x620+181+78")
        self.top.minsize(1, 1)
        self.top.maxsize(1585, 870)
        self.top.resizable(1, 1)
        self.top.title("LifePy")
        self.top.configure(relief="ridge")

        self.TFrame1 = ttk.Frame(top)
        self.TFrame1.place(relx=0.009, rely=0.014, relheight=0.237, relwidth=0.152)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="0")
        self.TFrame1.configure(relief="groove")

        self.Button1 = tk.Button(self.TFrame1)
        self.Button1.place(relx=0.061, rely=0.242, height=29, width=139)
        self.Button1.configure(relief="groove")
        self.Button1.configure(text='''Play''')
        self.Button1.bind("<Button-1>", self.play())

        self.Button1_1 = tk.Button(self.TFrame1)
        self.Button1_1.place(relx=0.061, rely=0.485, height=29, width=139)
        self.Button1_1.configure(activebackground="#f9f9f9")
        self.Button1_1.configure(text='''Stop''')

        self.Button1_2 = tk.Button(self.TFrame1)
        self.Button1_2.place(relx=0.061, rely=0.727, height=29, width=139)
        self.Button1_2.configure(activebackground="#f9f9f9")
        self.Button1_2.configure(text='''Reset''')

        self.age_label = ttk.Label(self.TFrame1)
        self.age_label.place(relx=0.061, rely=0.061, height=17, width=137)
        self.age_label.configure(background="#d9d9d9")
        self.age_label.configure(foreground="#000000")
        self.age_label.configure(font="TkDefaultFont")
        self.age_label.configure(relief="flat")
        self.age_label.configure(justify='center')
        self.age_label.configure(text='''Control''')

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bg_color, fg=_fg_color, relief="flat")
        self.top.configure(menu=self.menubar)

        self.sub_menu = tk.Menu(top, tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu,
                                 activebackground="#ececec",
                                 activeforeground="#000000",
                                 background="#d9d9d9",
                                 compound="left",
                                 foreground="#000000",
                                 label="Game")
        self.sub_menu.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            foreground="#000000",
            label="Load")
        self.sub_menu.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            foreground="#000000",
            label="Save")
        self.sub_menu1 = tk.Menu(top, tearoff=0)
        self.menubar.add_cascade(menu=self.sub_menu1,
                                 activebackground="#ececec",
                                 activeforeground="#000000",
                                 background="#d9d9d9",
                                 compound="left",
                                 foreground="#000000",
                                 label="Help")
        self.sub_menu1.add_command(
            activebackground="#ececec",
            activeforeground="#000000",
            background="#d9d9d9",
            command=self.show_about,
            foreground="#000000",
            label="About")

        self.TFrame2 = ttk.Frame(top)
        self.TFrame2.place(relx=0.009, rely=0.273, relheight=0.71, relwidth=0.152)
        self.TFrame2.configure(relief='groove')
        self.TFrame2.configure(borderwidth="0")
        self.TFrame2.configure(relief="groove")

        self.TLabel1 = ttk.Label(self.TFrame2)
        self.TLabel1.place(relx=0.061, rely=0.021, height=17, width=147)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(text="Speed")

        self.age_label = ttk.Label(self.TFrame2)
        self.age_label.place(relx=0.061, rely=0.321, height=17, width=147)
        self.age_label.configure(background="#d9d9d9")
        self.age_label.configure(foreground="#000000")
        self.age_label.configure(font="TkDefaultFont")
        self.age_label.configure(relief="flat")
        self.age_label.configure(text="Age: {}".format(self.age))

        self.canvas = grid_field.CanvasGrid(top, 60, 100, 10)
        self.canvas.place(relx=0.166, rely=0.01,
                           relheight=0.99, relwidth=0.9
                           )
        self.canvas.configure(borderwidth="2")
        # self.canvas.configure(relief="ridge")
        # self.canvas.configure(selectbackground="#c4c4c4")

        # self.TEntry1 = ttk.Entry(self.TFrame2)
        # self.TEntry1.place(relx=0.083, rely=0.133, width=139, height=17)
        # self.TEntry1.configure(takefocus="")
        # self.TEntry1.configure(justify='right')
        # self.TEntry1.configure(cursor="xterm")

        self.TScale1 = ttk.Scale(self.TFrame2, from_=0, to=10, variable=self.age)
        self.TScale1.place(relx=0.083, rely=0.133, width=139, height=17, bordermode='ignore')
        self.TScale1.configure(value="1")
        self.TScale1.configure(length="170")
        self.TScale1.configure(takefocus="")

    def show_about(self):
        window = tk.Toplevel(self.top)
        window.title("About")
        window.geometry("200x100")
        help_label = ttk.Label(window)
        help_label.configure(text='''This is Game of Life''')
        help_label.place(relx=0.061, rely=0.061)

    def update_speed(self):
        self.TLabel1.config(text="Speed: {}".format(self.TScale1.get()))

    def play(self):
        pass
