#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 07, 2020 01:16:23 AM CET  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_treeview_desc) $desc
set vTcl(actual_gui_font_treeview_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m52" -relief ridge -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 1083x696+181+78
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1585 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "MainWindow" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr49 \
        -borderwidth 2 -relief groove -width 165 -height 165 
    vTcl:DefineAlias "$top.tFr49" "TFrame1" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.tFr49
    button $site_3_0.but50 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief groove \
        -text Play 
    vTcl:DefineAlias "$site_3_0.but50" "Button1" vTcl:WidgetProc "MainWindow" 1
    button $site_3_0.but55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Stop 
    vTcl:DefineAlias "$site_3_0.but55" "Button1_1" vTcl:WidgetProc "MainWindow" 1
    button $site_3_0.but56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Reset 
    vTcl:DefineAlias "$site_3_0.but56" "Button1_2" vTcl:WidgetProc "MainWindow" 1
    ttk::label $site_3_0.tLa59 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -justify center -text Control 
    vTcl:DefineAlias "$site_3_0.tLa59" "TLabel2" vTcl:WidgetProc "MainWindow" 1
    place $site_3_0.but50 \
        -in $site_3_0 -x 10 -y 40 -width 139 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 10 -y 80 -width 139 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 10 -y 120 -width 139 -height 29 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa59 \
        -in $site_3_0 -x 10 -y 10 -width 137 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    set site_3_0 $top.m52
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men54" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font {} -foreground $vTcl(pr,menufgcolor) -label Game 
    menu $site_3_0.men54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men54 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font {} \
        -foreground $vTcl(pr,menufgcolor) -label Load 
    $site_3_0.men54 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {{}} -font {} \
        -foreground $vTcl(pr,menufgcolor) -label Save 
    $site_3_0 add cascade \
        -menu "$site_3_0.men54" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font {} -foreground $vTcl(pr,menufgcolor) -label Game \
        -menu "$site_3_0.men53" -activebackground $vTcl(analog_color_m) \
        -activeforeground #000000 -background $vTcl(pr,menubgcolor) \
        -command {{}} -font {} -foreground $vTcl(pr,menufgcolor) -label Help 
    menu $site_3_0.men53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0.men53 add command \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -command {#show_about} -font {} \
        -foreground $vTcl(pr,menufgcolor) -label About 
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $top.tFr57 \
        -borderwidth 2 -relief groove -width 165 -height 485 
    vTcl:DefineAlias "$top.tFr57" "TFrame2" vTcl:WidgetProc "MainWindow" 1
    set site_3_0 $top.tFr57
    ttk::label $site_3_0.tLa58 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -text {Draw your world} 
    vTcl:DefineAlias "$site_3_0.tLa58" "TLabel1" vTcl:WidgetProc "MainWindow" 1
    place $site_3_0.tLa58 \
        -in $site_3_0 -x 10 -y 10 -width 147 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    canvas $top.can61 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 661 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 881 
    vTcl:DefineAlias "$top.can61" "Canvas1" vTcl:WidgetProc "MainWindow" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr49 \
        -in $top -x 10 -y 10 -width 165 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tFr57 \
        -in $top -x 10 -y 190 -width 165 -relwidth 0 -height 485 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can61 \
        -in $top -x 180 -y 10 -width 881 -relwidth 0 -height 661 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

